# Generated by Django 5.2.11 on 2026-02-16 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storicolaborationrequest_storycolaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storicolaborationrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RenameField(
            model_name='storicolaborationrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='storicolaborationrequest',
            old_name='user',
            new_name='requester',
        ),
        migrations.AddField(
            model_name='storicolaborationrequest',
            name='responced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='storicolaborationrequest',
            unique_together={('story', 'requester')},
        ),
        migrations.DeleteModel(
            name='StoryColaborators',
        ),
    ]
