# Generated by Django 5.2.11 on 2026-02-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_storicolaborationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storicolaborationrequest',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_requestes', to='story.story'),
        ),
    ]
